### ISSUE TITLE
EndPoint  per le stop 

### ISSUE THREAD

**Issue by mrJungle** [gtfscreator/gtfs-server#15]
obiettivo:

A partire da una linea (routes) e una data (es. oggi) di un determinato feed desidero ricavare tutte le fermate.

al momento sul client l'unica maniera che vedo è ciclare sull'api 

`/api/feeds/1/stop-times-active-today/?page=28&route_id=B220`

e poi aggregare nel client "per fermata" in modo da tirar fuori un elenco. 
In questo caso ciclo 28 volte. 

Per te è ok oppure troppo oneroso e meglio preparare un'api apposta

(es. `/api/feeds/1/stop-times-active-today/stop/?page=28&route_id=B220` )

**Comment by bianchimro** [comment]
> A partire da una linea (routes) e una data (es. oggi) di un determinato feed desidero ricavare tutte le fermate.

Le puoi avere con:
`api/feeds/<id>/stops-active-today/?route_id=<route-id>`

ad esempio:

http://gtfs.inmagik.com/api/feeds/1/stops-active-today/?route_id=T1

**Comment by mrJungle** [comment]
me l'ero persa

ok
