### ISSUE TITLE
stop-time API

### ISSUE THREAD

**Issue by mrJungle** [gtfscreator/gtfs-server#3]
serve una API che tiri fuori gli orari in fermata per linea.

Un esempio potrebbe essere:

/api/feeds/<feed-id>/stop-times/<stop-id>/<trip-id>/<date>/<hour>/<minute>

(non so se si scrive cosi la post)
/api/feeds/<feed-id>/stop-times/?stop-id=x,trip-id=y,date=20150929,time=12.15

**Comment by bianchimro** [comment]
`/api/feeds/<feed-id>/stop-times/[?stop=<stop-id>][&trip=<trip-id>][&arrival_time=<time>]`

`/api/feeds/<feed-id>/stop-times-active/<year>-<month>-<day>/[?stop=<stop-id>][&trip=<trip-id>][&arrival_time=<time>]`

**Comment by mrJungle** [comment]
`/api/feeds/<feeds-id>/routes/<routes-id>/stops/-----/date/<date>'

(id della route di quel GTFS - Route_id)

**Comment by mrJungle** [comment]
Sempre per ampliare il ragionamento scrivo quelle che mi sembrano utili;
(per farla semplice uso il '/today/' per dare l'idea di 'oggi' , cmq da valutare)

Avendo l'id di una route ottenere i trips attivi oggi:
`/api/feeds/today/routes/stops/`

Avendo l'id di una route ottenere le stop su tutti i trips che servono la linea oggi:
`/api/feeds/today/trips/stops/`

Avendo l'id una fermata ottenere tutte le routes di oggi e le relative trips annidate dentro con l'orario di passaggio alla fermata;
`/api/feeds/today/stops/<stop-id>/routes`

Avendo l'id una fermata ottenere la routes indicata con la validità di oggi e le relative trips annidate dentro con l'orario di passaggio alla fermata;
`/api/feeds/today/stops/<stop-id>/routes/<routes-id>/`

Com queste dovrei riuscire a iniziare a presentare il dato (ho una mezza idea grafica sul come provare a rappresentarlo)

**Comment by bianchimro** [comment]
In generale ok, tutti gli endpoint mi sembrano sensati.
anche "today" va bene al posto di una data per indicare oggi (anche se potrebbe calcolarselo il client e passare una data)

per i vari endpoint meglio fare una issue per ogni endpoint, se no ci incasiniamo.
non mi tornano gli url/parametri che hai descritto ma li vediamo nelle singole issues.

**Comment by mrJungle** [comment]
ok
