### ISSUE TITLE
Apy Type

### ISSUE THREAD

**Issue by mrJungle** [gtfscreator/gtfs-server#4]
Estrai tutti i tipi di linee TPL presenti nel gtfs considerato.

http://gtfs.inmagik.com/api/feeds/1/routes/_type

(ho bisogno di sapere le tipologie di tratte presenti nel GTFS, ma dato che cè il pagination non riesco a farlo lato javascritp senza prima tirarmi giu tutte le pagine)

**Comment by bianchimro** [comment]
intendi i tipi di routes per cui ci sono routes?

**Comment by mrJungle** [comment]
si.

```
0 - Tram, Streetcar, Light rail. Any light rail or street level system within a metropolitan area.
1 - Subway, Metro. Any underground rail system within a metropolitan area.
2 - Rail. Used for intercity or long-distance travel.
3 - Bus. Used for short- and long-distance bus routes.
4 - Ferry. Used for short- and long-distance boat service.
5 - Cable car. Used for street-level cable cars where the cable runs beneath the car.
6 - Gondola, Suspended cable car. Typically used for aerial cable cars where the car is suspended from the cable.
7 - Funicular. Any rail system designed for steep inclines.
```

**Comment by bianchimro** [comment]
creato endpoint a:
(_rtype e non type)

http://gtfs.inmagik.com/api/feeds/1/routes/_rtype/

la convenzione _nomecampo
potrebbe voler dire sempre i valori di quel campo.
